### ISSUE TITLE
Deep Relation Filtering Feature

### ISSUE THREAD

**Issue by Kladislav** [franciskisiara/osmose#4]
**Hello**, maybe in the future there will be an opportunity to upgrade **RelationshipFilter** to deep filtering: 
```
public function residue ()
{
    return [
        'role' => 'relationship:roles.abiltities,title'
    ]
}
```

**Comment by franciskisiara** [comment]
@Kladislav this is under consideration and will be featured in one of the future releases.

EDIT: For now you can use the **CallbackFilter** to perform deep filters.
