### ISSUE TITLE
User defined dates filters:

### ISSUE THREAD

**Issue by jjoek** [franciskisiara/osmose#5]
This feature was previously there in the previous versions but seems to have been faded out from version 1.1 and replaced with ranges:

Apparently ranges will work well with data sets whose filters are limited to certain durations, but for scenarios like I am in, where I need the user to specify the dates as per how he/she wants is currently """"probably not possible""""""" or not specified in the docs:

To work around this though I've added the following to the range function in the meantime as we wait for a fix:

       
 
        if (request()->has($range))
         {
            if(is_array($range)) {

               $timespan = [ Carbon::parse(request()->all()[$range[0]]), Carbon::parse(request()->all()[$range[1]]) ];

            } else {

                $timespan = config("osmose.ranges.".request($range));
            }

            $this->builder = $this->builder->whereBetween(
                'created_at', $timespan
            );
        }

        return $this;`

**Comment by franciskisiara** [comment]
Hey @jjoek, I'm glad you are finding **osmose** useful in your day-to-day app development.

This feature was deprecated as it was prone to too many user errors and the API was not as intuitive as I would've wished it to be. I will update the docs to indicate this.

I introduced `range` as a quick solution to provide some semblance of date filtering though I must admit `range` is far from being ideal in complex filters.

However, I am working on a cleaner API for date filtering that will feature in the next major version of osmose scheduled for release in the next 13 days.

**Comment by franciskisiara** [comment]
@jjoek, version 2.0 of osmose is now up. This version introduces a more powerful APi for date filters that address your request as well as a bound method to execute compulsory filters. You can read more in the docs.
https://github.com/franciskisiara/osmose#filtering-dates
